<?php

/**
 * This is the model base class for the table "guru".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Gurus".
 *
 * Columns in table "guru" available as properties of the model,
 * followed by relations of table "guru" available as properties of the model.
 *
 * @property integer $id_guru
 * @property string $nip
 * @property string $nama
 * @property integer $status
 * @property string $tempat_lahir
 * @property string $tanggal_lahir
 * @property string $alamat
 * @property string $kontak
 * @property string $email
 * @property string $gelar_depan
 * @property string $gelar_belakang
 * @property string $foto
 *
 * @property Kelas $idKelas
 * @property Jadwal[] $jadwals
 * @property User[] $users
 */
abstract class BaseGurus extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'guru';
    }

    public static function representingColumn() {
        return 'nip';
    }

    public function rules() {
        return array(
            array('nip, nama, status', 'required'),
            array(' status', 'numerical', 'integerOnly'=>true),
            array('nip, gelar_depan, gelar_belakang', 'length', 'max'=>10),
            array('nama, tempat_lahir, kontak, email, foto', 'length', 'max'=>45),
            array('alamat', 'length', 'max'=>100),
            array('tanggal_lahir', 'safe'),
            array('tempat_lahir, tanggal_lahir, alamat, kontak, email, gelar_depan, gelar_belakang, foto', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_guru, nip, nama, status, tempat_lahir, tanggal_lahir, alamat, kontak, email, gelar_depan, gelar_belakang, foto', 'safe', 'on'=>'search'),
			array('foto', 'file', 'on' => 'insert', 'on' => 'create', 'allowEmpty' => true, 'safe'=>true,
                'maxSize'=> 204800, 
                'maxFiles'=> 1, 
                'types'=>'jpg, png',
                'tooLarge'=> 'File tidak boleh lebih dari 200KB.',
                'wrongType'=>'Foto hanya boleh .jpg dan .png.'
            ),
        );
    }

    public function relations() {
        return array(
            'jadwals' => array(self::HAS_MANY, 'Jadwal', 'id_guru'),
            'users' => array(self::HAS_MANY, 'User', 'id_guru'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_guru' => Yii::t('app', 'Id Guru'),
                'nip' => Yii::t('app', 'Nip'),
                'nama' => Yii::t('app', 'Nama'),
                'status' => Yii::t('app', 'Status'),
                'tempat_lahir' => Yii::t('app', 'Tempat Lahir'),
                'tanggal_lahir' => Yii::t('app', 'Tanggal Lahir'),
                'alamat' => Yii::t('app', 'Alamat'),
                'kontak' => Yii::t('app', 'Kontak'),
                'email' => Yii::t('app', 'Email'),
                'gelar_depan' => Yii::t('app', 'Gelar Depan'),
                'gelar_belakang' => Yii::t('app', 'Gelar Belakang'),
                'foto' => Yii::t('app', 'Foto'),
                'idKelas' => null,
                'jadwals' => null,
                'users' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_guru', $this->id_guru);
        $criteria->compare('nip', $this->nip, true);
        $criteria->compare('nama', $this->nama, true);
        $criteria->compare('status', $this->status);
        $criteria->compare('tempat_lahir', $this->tempat_lahir, true);
        $criteria->compare('tanggal_lahir', $this->tanggal_lahir, true);
        $criteria->compare('alamat', $this->alamat, true);
        $criteria->compare('kontak', $this->kontak, true);
        $criteria->compare('email', $this->email, true);
        $criteria->compare('gelar_depan', $this->gelar_depan, true);
        $criteria->compare('gelar_belakang', $this->gelar_belakang, true);
        $criteria->compare('foto', $this->foto, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}