<?php

/**
 * This is the model base class for the table "kelas".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Kelass".
 *
 * Columns in table "kelas" available as properties of the model,
 * followed by relations of table "kelas" available as properties of the model.
 *
 * @property integer $id_kelas
 * @property integer $id_guru
 * @property string $nama
 * @property integer $kapasitas
 * @property integer $status
 *
 * @property Guru $idGuru
 * @property PembagainKelas[] $pembagainKelases
 */
abstract class BaseKelass extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'kelas';
    }

    public static function representingColumn() {
        return 'nama';
    }

    public function rules() {
        return array(
            array('id_guru, nama, status', 'required'),
            array('id_guru, kapasitas, status', 'numerical', 'integerOnly'=>true),
            array('nama', 'length', 'max'=>45),
            array('kapasitas', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_kelas, id_guru, nama, kapasitas, status', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'idGuru' => array(self::BELONGS_TO, 'Gurus', 'id_guru'),
            'pembagainKelases' => array(self::HAS_MANY, 'PembagainKelas', 'id_kelas'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_kelas' => Yii::t('app', 'Id Kelas'),
                'id_guru' => Yii::t('app', 'Id Guru'),
                'nama' => Yii::t('app', 'Nama'),
                'kapasitas' => Yii::t('app', 'Kapasitas'),
                'status' => Yii::t('app', 'Status'),
                'idGuru' => null,
                'pembagainKelases' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_kelas', $this->id_kelas);
        $criteria->compare('id_guru', $this->id_guru);
        $criteria->compare('nama', $this->nama, true);
        $criteria->compare('kapasitas', $this->kapasitas);
        $criteria->compare('status', $this->status);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}