<?php

/**
 * This is the model base class for the table "semester".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Semesters".
 *
 * Columns in table "semester" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_semester
 * @property string $nama
 * @property integer $status
 *
 */
abstract class BaseSemesters extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'semester';
    }

    public static function representingColumn() {
        return 'nama';
    }

    public function rules() {
        return array(
            array('nama, status', 'required'),
            array('status', 'numerical', 'integerOnly'=>true),
            array('nama', 'length', 'max'=>45),
            array('id_semester, nama, status', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_semester' => Yii::t('app', 'Id Semester'),
                'nama' => Yii::t('app', 'Nama'),
                'status' => Yii::t('app', 'Status'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_semester', $this->id_semester);
        $criteria->compare('nama', $this->nama, true);
        $criteria->compare('status', $this->status);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}