<?php

/**
 * This is the model base class for the table "jadwal".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Jadwals".
 *
 * Columns in table "jadwal" available as properties of the model,
 * followed by relations of table "jadwal" available as properties of the model.
 *
 * @property integer $id_jadwal
 * @property integer $id_guru
 * @property integer $id_mapel
 * @property integer $id_kelas
 * @property integer $id_tahun_ajaran
 * @property integer $status
 *
 * @property Mapel $idMapel
 * @property TahunAjaran $idTahunAjaran
 * @property Guru $idGuru
 * @property Kelas $idKelas
 */
abstract class BaseJadwals extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'jadwal';
    }

    public static function representingColumn() {
        return 'id_jadwal';
    }

    public function rules() {
        return array(
            array('id_guru, id_mapel, id_kelas, id_tahun_ajaran, status', 'required'),
            array('id_guru, id_mapel, id_kelas, id_tahun_ajaran, status', 'numerical', 'integerOnly'=>true),
            array('id_jadwal, id_guru, id_mapel, id_kelas, id_tahun_ajaran, status', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'idMapel' => array(self::BELONGS_TO, 'Mapels', 'id_mapel'),
            'idTahunAjaran' => array(self::BELONGS_TO, 'Tahans', 'id_tahun_ajaran'),
            'idGuru' => array(self::BELONGS_TO, 'Gurus', 'id_guru'),
            'idKelas' => array(self::BELONGS_TO, 'Kelass', 'id_kelas'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_jadwal' => Yii::t('app', 'Id Jadwal'),
                'id_guru' => Yii::t('app', 'Id Guru'),
                'id_mapel' => Yii::t('app', 'Id Mapel'),
                'id_kelas' => Yii::t('app', 'Id Kelas'),
                'id_tahun_ajaran' => Yii::t('app', 'Id Tahun Ajaran'),
                'status' => Yii::t('app', 'Status'),
                'idMapel' => null,
                'idTahunAjaran' => null,
                'idGuru' => null,
                'idKelas' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_jadwal', $this->id_jadwal);
        $criteria->compare('id_guru', $this->id_guru);
        $criteria->compare('id_mapel', $this->id_mapel);
        $criteria->compare('id_kelas', $this->id_kelas);
        $criteria->compare('id_tahun_ajaran', $this->id_tahun_ajaran);
        $criteria->compare('status', $this->status);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}