<?php

/**
 * This is the model base class for the table "mapel".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mapels".
 *
 * Columns in table "mapel" available as properties of the model,
 * followed by relations of table "mapel" available as properties of the model.
 *
 * @property integer $id_mapel
 * @property string $nama
 * @property integer $sifat
 * @property integer $status
 *
 * @property Jadwal[] $jadwals
 */
abstract class BaseMapels extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'mapel';
    }

    public static function representingColumn() {
        return 'nama';
    }

    public function rules() {
        return array(
            array('nama, sifat, status', 'required'),
            array('sifat, status', 'numerical', 'integerOnly'=>true),
            array('nama', 'length', 'max'=>45),
            array('id_mapel, nama, sifat, status', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'jadwals' => array(self::HAS_MANY, 'Jadwal', 'id_mapel'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_mapel' => Yii::t('app', 'Id Mapel'),
                'nama' => Yii::t('app', 'Nama'),
                'sifat' => Yii::t('app', 'Sifat'),
                'status' => Yii::t('app', 'Status'),
                'jadwals' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_mapel', $this->id_mapel);
        $criteria->compare('nama', $this->nama, true);
        $criteria->compare('sifat', $this->sifat);
        $criteria->compare('status', $this->status);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}