<?php

/**
 * This is the model base class for the table "tahun_ajaran".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Tahans".
 *
 * Columns in table "tahun_ajaran" available as properties of the model,
 * followed by relations of table "tahun_ajaran" available as properties of the model.
 *
 * @property integer $id_tahun_ajaran
 * @property string $nama
 * @property integer $status
 * @property string $tanggal_mulai
 * @property string $tanggal_akhir
 *
 * @property Jadwal[] $jadwals
 * @property PembagainKelas[] $pembagainKelases
 */
abstract class BaseTahans extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tahun_ajaran';
    }

    public static function representingColumn() {
        return 'nama';
    }

    public function rules() {
        return array(
            array('nama, status', 'required'),
            array('status', 'numerical', 'integerOnly'=>true),
            array('nama', 'length', 'max'=>45),
            array('tanggal_mulai, tanggal_akhir', 'safe'),
            array('tanggal_mulai, tanggal_akhir', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_tahun_ajaran, nama, status, tanggal_mulai, tanggal_akhir', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'jadwals' => array(self::HAS_MANY, 'Jadwal', 'id_tahun_ajaran'),
            'pembagainKelases' => array(self::HAS_MANY, 'PembagainKelas', 'id_tahun_ajaran'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_tahun_ajaran' => Yii::t('app', 'Id Tahun Ajaran'),
                'nama' => Yii::t('app', 'Nama'),
                'status' => Yii::t('app', 'Status'),
                'tanggal_mulai' => Yii::t('app', 'Tanggal Mulai'),
                'tanggal_akhir' => Yii::t('app', 'Tanggal Akhir'),
                'jadwals' => null,
                'pembagainKelases' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_tahun_ajaran', $this->id_tahun_ajaran);
        $criteria->compare('nama', $this->nama, true);
        $criteria->compare('status', $this->status);
        $criteria->compare('tanggal_mulai', $this->tanggal_mulai, true);
        $criteria->compare('tanggal_akhir', $this->tanggal_akhir, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}