<?php

/**
 * This is the model base class for the table "pembagain_kelas".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Bagkels".
 *
 * Columns in table "pembagain_kelas" available as properties of the model,
 * followed by relations of table "pembagain_kelas" available as properties of the model.
 *
 * @property integer $id_pembagian_kelas
 * @property integer $id_siswa
 * @property integer $id_kelas
 * @property integer $id_tahun_ajaran
 * @property integer $status
 *
 * @property Siswa $idSiswa
 * @property TahunAjaran $idTahunAjaran
 * @property Kelas $idKelas
 */
abstract class BaseBagkels extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'pembagain_kelas';
    }

    public static function representingColumn() {
        return 'id_pembagian_kelas';
    }

    public function rules() {
        return array(
            array('id_siswa, id_kelas, id_tahun_ajaran, status', 'required'),
            array('id_siswa, id_kelas, id_tahun_ajaran, status', 'numerical', 'integerOnly'=>true),
            array('id_pembagian_kelas, id_siswa, id_kelas, id_tahun_ajaran, status', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'idSiswa' => array(self::BELONGS_TO, 'Siswas', 'id_siswa'),
            'idTahunAjaran' => array(self::BELONGS_TO, 'Tahans', 'id_tahun_ajaran'),
            'idKelas' => array(self::BELONGS_TO, 'Kelass', 'id_kelas'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_pembagian_kelas' => Yii::t('app', 'Id Pembagain Kelas'),
                'id_siswa' => Yii::t('app', 'Id Siswa'),
                'id_kelas' => Yii::t('app', 'Id Kelas'),
                'id_tahun_ajaran' => Yii::t('app', 'Id Tahun Ajaran'),
                'status' => Yii::t('app', 'Status'),
                'idSiswa' => null,
                'idTahunAjaran' => null,
                'idKelas' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_pembagian_kelas', $this->id_pembagian_kelas);
        $criteria->compare('id_siswa', $this->id_siswa);
        $criteria->compare('id_kelas', $this->id_kelas);
        $criteria->compare('id_tahun_ajaran', $this->id_tahun_ajaran);
        $criteria->compare('status', $this->status);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}