<?php

/**
 * This is the model base class for the table "siswa".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Siswas".
 *
 * Columns in table "siswa" available as properties of the model,
 * followed by relations of table "siswa" available as properties of the model.
 *
 * @property integer $id_siswa
 * @property string $nis
 * @property string $nama
 * @property integer $status
 * @property string $tahun_masuk
 * @property string $tempat_lahir
 * @property string $tanggal_lahir
 * @property string $alamat
 * @property string $orang_tua
 * @property string $foto
 *
 * @property PembagainKelas[] $pembagainKelases
 */
abstract class BaseSiswas extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'siswa';
    }

    public static function representingColumn() {
        return 'nis';
    }

    public function rules() {
        return array(
            array('nis, nama, status, orang_tua', 'required'),
            array('status', 'numerical', 'integerOnly'=>true),
            array('nis, nama, tempat_lahir, orang_tua, foto', 'length', 'max'=>45),
            array('tahun_masuk', 'length', 'max'=>10),
            array('alamat', 'length', 'max'=>100),
            array('tanggal_lahir', 'safe'),
            array('tahun_masuk, tempat_lahir, tanggal_lahir, alamat, foto', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_siswa, nis, nama, status, tahun_masuk, tempat_lahir, tanggal_lahir, alamat, orang_tua, foto', 'safe', 'on'=>'search'),
			array('foto', 'file', 'on' => 'insert', 'on' => 'create', 'allowEmpty' => true, 'safe'=>true,
                'maxSize'=> 204800, 
                'maxFiles'=> 1, 
                'types'=>'jpg, png',
                'tooLarge'=> 'File tidak boleh lebih dari 200KB.',
                'wrongType'=>'Foto hanya boleh .jpg dan .png.'
            ),
        );
    }

    public function relations() {
        return array(
            'pembagainKelases' => array(self::HAS_MANY, 'PembagainKelas', 'id_siswa'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_siswa' => Yii::t('app', 'Id Siswa'),
                'nis' => Yii::t('app', 'Nis'),
                'nama' => Yii::t('app', 'Nama'),
                'status' => Yii::t('app', 'Status'),
                'tahun_masuk' => Yii::t('app', 'Tahun Masuk'),
                'tempat_lahir' => Yii::t('app', 'Tempat Lahir'),
                'tanggal_lahir' => Yii::t('app', 'Tanggal Lahir'),
                'alamat' => Yii::t('app', 'Alamat'),
                'orang_tua' => Yii::t('app', 'Orang Tua'),
                'foto' => Yii::t('app', 'Foto'),
                'pembagainKelases' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_siswa', $this->id_siswa);
        $criteria->compare('nis', $this->nis, true);
        $criteria->compare('nama', $this->nama, true);
        $criteria->compare('status', $this->status);
        $criteria->compare('tahun_masuk', $this->tahun_masuk, true);
        $criteria->compare('tempat_lahir', $this->tempat_lahir, true);
        $criteria->compare('tanggal_lahir', $this->tanggal_lahir, true);
        $criteria->compare('alamat', $this->alamat, true);
        $criteria->compare('orang_tua', $this->orang_tua, true);
        $criteria->compare('foto', $this->foto, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}